twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [
        'Form/kit_layout.html.twig',
        'Form/recaptcha_type.html.twig'
    ]
    globals:
        recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

when@test:
    twig:
        strict_variables: true
